M48
; DRILL file {KiCad 9.0.6} date 2025-12-30T21:34:04-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T21:34:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X123.5Y-32.07
X124.0Y-56.07
X136.5Y-32.07
X137.5Y-56.07
M30
